---
- name: Set targeted DB IP address
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set targeted DB IP address for failover
      set_fact:
        db_ipaddr: "{{ db_target }}"
- name: Dynamic hosts from external file
  hosts: "{{ db_ipaddr }}"

  tasks:
    - debug:
        msg: "Running on {{ inventory_hostname }}"
